version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: bookings-db
    environment:
      POSTGRES_DB: bookings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
    external: false
